# Generated by Django 5.2 on 2025-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
