# Generated by Django 5.2 on 2025-09-17 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_author_library_profile_book_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to='first_app.library'),
        ),
    ]
