# Generated by Django 5.2 on 2025-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_brand_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='made_in',
            field=models.CharField(default='China', max_length=20),
        ),
    ]
